<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>let and const over var</h3>



    <!-- <script>
        if(10 < 40){
            const x = 120; //var => global scope variable, let & const => local scope / black scope variable

            document.write(`<h1>Inside the block = ${x}</h1>`);
        }

        document.write(`<h1>outside the block = ${x}</h1>`);   //let or const => Referance error

        document.write('<h1>block after the try catch</h1>')


  //try used to logical part  ,its therougth the error in catch block



    </script> -->


    
    <script>
        try{
            
                if(10 < 40){
                    const x = 120; //var => global scope variable, let & const => local scope / black scope variable
        
                    document.write(`<h1>Inside the block = ${x}</h1>`);
                }
        
                document.write(`<h1>outside the block = ${x}</h1>`);   //let or const => Referance error
        
        
        }catch(error){
            console.log('error =',error);

        }

        document.write('<h1>block after the try catch</h1>')
    </script>



</body>
</html>